---
- name: Redfish Storage volume Configurations
  hosts: idrac
  gather_facts: false
  vars_files:
    - ../vars_files/credentials.yml
  vars:
    state: "present"
    validate_certs: false
    raid_type: "RAID0"
    name: "VD-test"
    controller_id: "RAID.Integrated.1-1"
    drives:
      - Disk.Bay.0:Enclosure.Internal.0-0:RAID.Integrated.1-1
    capacity_bytes: 299439751168
    optimum_io_size_bytes: 65536
  roles:
    - dellemc.openmanage.redfish_storage_volume
